name: Debug OIDC Token
on:
  workflow_dispatch:

jobs:
  decode-oidc-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch OIDC Token Claims
        run: |
          echo "Fetching OIDC Token Claims..."
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq .
      
      - name: Decode OIDC Token
        run: |
          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | awk -F'.' '{print $2}' | base64 -d | jq .
