name: Debug OIDC Token  # Name of the workflow

on: 
  workflow_dispatch:  # Allows manual execution

jobs:
  decode-oidc-token:
    runs-on: ubuntu-latest  # GitHub runner
    permissions:
      id-token: write   # Required for GitHub OIDC authentication
      contents: read
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch OIDC Token Claims
        run: |
          echo "Fetching OIDC Token Claims..."
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq .
      
      - name: Decode OIDC Token
        run: |
          echo "Decoding OIDC Token..."
          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | awk -F'.' '{print $2}' | base64 -d | jq .
